// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"KUCIS_HubParallaxPassage","status":true,"description":"Allows free movement on the parallax-mapped hub map.","parameters":{}},
{"name":"KUCIS_QuizStageMode","status":true,"description":"Hides the player and disables movement on quiz stage maps.","parameters":{}},
{"name":"KUCIS_PromptInput","status":true,"description":"Adds a simple prompt input overlay for quiz stages.","parameters":{}},
{"name":"KUCIS_BadgePopup","status":true,"description":"Shows a centered badge popup above the game screen.","parameters":{}},
{"name":"KUCIS_PlayerMoveSpeed","status":true,"description":"Sets a calmer walking speed on the hub map.","parameters":{}},
{"name":"KUCIS_EndingCredits","status":true,"description":"Opens the guardian form and shows the final scrolling credits.","parameters":{}},
{"name":"KUCIS_SkipTitle","status":true,"description":"Starts the game directly on the map instead of showing the title screen.","parameters":{}}
];
